### ISSUE TITLE
about the cases

### ISSUE THREAD

**Issue by whucsu** [soanagno/rba-pinns#3]
Dear sir,
 thanks for sharing the code. May I ask where are the other cases codes ? like 3D Navier–Stokes mentioned in the publication .

**Comment by soanagno** [comment]
Hello, thanks for reaching out. Unfortunately, the 3D NS case is part of another project which is not open source. The Helmholtz and Allen-Cahn cases are available in Pytorch and Jax. We have also added the AC case with the enhancements of the paper in the Pytorch folder.
