### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by xztu2121** [soanagno/rba-pinns#4]
1.  In the file "allen-cahn_rba-sa.ipynb," I found that your boundary is directly read from the data file, but the upper spatial boundary in the data file is not equal to 1.
2.  In the file "allen-cahn_rba-sa.ipynb," why is loss_ub set to 0? There doesn't seem to be any related handling of the boundary in the code .  Is there an issue with this setting?

**Comment by soanagno** [comment]
Hi, thanks for reaching out.

1. The upper and lower boundary velocities read from the data file (uu2, uu3) are not used anywhere for solving AC, they were there for tests so we removed them. Also there is no Dirichlet condition equal to 1 for AC.

2. We've made a correction to the symmetry bc, you can now activate it in the updated code. Note that this bc is not needed for good convergence.

**Comment by xztu2121** [comment]
Thank you very much for your answer. Can I understand that the inclusion of boundary loss in the loss function may not significantly affect the overall convergence,?  In fact, the boundaries provide supervisory information, which appears to have a certain impact.

**Comment by soanagno** [comment]
Yes, for this problem the information from the initial condition is enough.
