### ISSUE TITLE
About the result

### ISSUE THREAD

**Issue by sdtges** [soanagno/rba-pinns#5]
Hi, I ran your code (allen-cahn_rba-sa), and the final relative L2 error is approximately 10^−2, which is inconsistent with the 10^-5 in your paper (the Table 1). What happened?

**Comment by soanagno** [comment]
Hello,

There is no inconsistency, please refer to the paper results. This model has no enhancements and is trained only for 30k iterations to compare RBA with SA (see  section 3.4, Fig. 8). The model "allen-cahn_rba-enhanced" is trained for 300k iterations and includes the PINN enhancements, which converges to the order of 1e-5.

We have added a small description for each file in the readme file.
